---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# riskparity

<!-- badges: start -->
<!-- badges: end -->

The goal of `{{riskparity}}` is to demonstrate different approaches to asset allocation to achieve risk parity.

## Installation

You can install the released version of riskparity from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("riskparity")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("samthorold/riskparity")
```
## Example

```{r example}
library(riskparity)
# asset allocation
w <- c(.55, .25, .2)
# asset standard deviations
s <- c(.24, .18, .15)
# asset correlation
C <- matrix(c(1, 0.85, 0.3, 0.85, 1, -0.15, 0.3, -0.15, 1), nrow = 3)

# total contribution to portfolio standard deviation
asset_stdev_contrib(w, s, C)

# marginal contribution to portfolio standard deviation
asset_stdev_contrib(w, s, C, marginal = TRUE)

# dispersion measures
effective_constituents(w)
entropy(w)
entropy(asset_stdev_contrib(w, s, C))

df <- read.csv("../data/equity.csv")[,-1]

head(df)

C <- cor(df)

cor_robust(C, 0)
cor_robust(C, 0.55)

V <- cov(df)

cov_robust(V, 0)
cov_robust(V, 0.55)

s <- apply(df, 2, sd)
S <- diag(s)
S

decomp <- eigen(C)
E <- diag(decomp$values)
R <- decomp$vectors

all(round(C, 2) == round(R %*% E %*% t(R), 2))

t <- dim(df)[1]
n <- dim(df)[2]

e_thresh <- 1 + n / t + 2 * sqrt(n / t)
e_thresh <- 0.55

e <- diag(E)
e[e < e_thresh] = 0
E_robust <- diag(e)

C_robust <- R %*% E_robust %*% t(R)
diag(C_robust) <- 1
C_robust

V_robust <- S %*% C_robust %*% S
V_robust

V <- cov(df)

S_inv <- diag(1 / sqrt(diag(V)))
all(round(S_inv %*% V %*% S_inv, 2) == round(cor(df), 2))
```


